###producer
#该应用是否启用生产者
plarform:
  server:
    url: 39.105.97.133
    port: 8070

rocketmq:
  ##该应用是否启用消费者
  consumer:
    isOnOff: off
    groupName: transferplatform
    #mq的nameserver地址
    namesrvAddr: 39.105.97.133:8091
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: DemoTopic~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1